
services:
    users:
        image: lmsusers:latest
        container_name: users_in_lms_network
        build:
            context: ..
            dockerfile: Dockerfile
        ports:
            - "8084:8080"
        environment:
            SPRING_PROFILES_ACTIVE: bootstrap
        networks:
            - lms_network

networks:
    lms_network:
        external: true

volumes:
    postgres_volume: